### PR TITLE
Add device arg to torch train and predict #188 

### PR DESCRIPTION
**Pull request by Mohinta2892**
Pre-Merge Checklist:

- [x] if this PR adds a feature: request merge into the latest development branch (`patch-1.3.2`)
- [ ] if this PR fixes a bug: request merge into the latest patch branch (`patch-X.Y.Z`)
- [x] PR branch name is short and describes the feature/bug addressed in this PR #188 
- [x] commit messages [are consistent](https://chris.beams.io/posts/git-commit/)
- [ ] changes reviewed by another contributor
- [x] tests cover changes
- [x] all tests pass

### CODE REVIEW

**Comment by pattonw** [comment]
please target patch-1.3.2, and run black to make spacings consistent

**Comment by Mohinta2892** [comment]
Hi Will,

Thanks, reformatted with black!

**Comment by pattonw** [comment]
Hi Samia, Thanks! but no need to reformat unrelated files, just the ones you modified would be great

**Comment by Mohinta2892** [comment]
Sorry, fixed.

**Comment by pattonw** [comment]
squashed and merged into the patch branch

**Pull request closed without merging**
