### PR TITLE
ZarrSource support Stores/path

### PR DESCRIPTION
**Pull request by mzouink**
Fixing 
https://github.com/funkey/gunpowder/issues/184
Pre-Merge Checklist:

- [ ] if this PR adds a feature: request merge into the latest development branch (`vX.Y-dev`)
- [ ] if this PR fixes a bug: request merge into the latest patch branch (`patch-X.Y.Z`)
- [ ] PR branch name is short and describes the feature/bug addressed in this PR
- [ ] commit messages [are consistent](https://chris.beams.io/posts/git-commit/)
- [ ] changes reviewed by another contributor
- [ ] tests cover changes
- [ ] all tests pass

### CODE REVIEW

**Comment by pattonw** [comment]
I like the idea of using stores as a more general interface for the Zarr read/write nodes, but I'm not sure if I like the new interface with a mandatory filename and optional store. So I guess if I had a store `my_zarr_store` I wanted to use it would be something like `ZarrSource(filename="placeholder_filename", datasets=..., store=my_zarr_store)`?

I think it would be nicer to mimic the [open](https://zarr.readthedocs.io/en/stable/api/convenience.html#zarr.convenience.open) interface where store is a "[Optional](https://docs.python.org/3/library/typing.html#typing.Optional)[[Union](https://docs.python.org/3/library/typing.html#typing.Union)[BaseStore, [MutableMapping](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping), [str](https://docs.python.org/3/library/stdtypes.html#str)]]" and we get just rename the `filename` arg.

Seems like you might have what you want if you just remove the `ensure_string` helper function around `filename`.

**Comment by mzouink** [comment]
I agree with you @pattonw, i just didn't want to brake the existant work and tutorials
i will try to do it in a better way but without breaking things

**Comment by mzouink** [comment]
@pattonw  can you please check it

**Comment by pattonw** [comment]
I think that looks good. could you add some quick tests for reading/writing to different store types. and rebase to target branch v1.3-dev since this is a breaking change

**Comment by pattonw** [comment]
merged into v1.3-dev

**Pull request closed without merging**
